# tasks file for tomcat_install
---
- name: Check if Java is installed
  become: yes
  shell: java -version
  register: java_version
  ignore_errors: true

- name: Install Java on CentOS
  become: yes
  when: "'CentOS' in ansible_distribution"
  package:
    name: java-11-openjdk-devel
    state: present

- name: Install Java on Ubuntu
  become: yes
  when: "'Ubuntu' in ansible_distribution"
  package:
    name: openjdk-11-jdk
    state: present

- name: Download Apache Tomcat tarball
  become: yes
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz"
    dest: "/tmp/apache-tomcat-9.0.54.tar.gz"

- name: Extract Apache Tomcat tarball
  become: yes
  unarchive:
    src: "/tmp/apache-tomcat-9.0.54.tar.gz"
    dest: "/opt/"
    remote_src: yes

- name: Set environment variables for Tomcat
  become: yes
  template:
    src: ../templates/setenv.sh.j2  # Adjust path as per your structure
    dest: "/opt/apache-tomcat-9.0.54/bin/setenv.sh"

- name: Configure Tomcat service (systemd)
  become: yes
  template:
    src: ../templates/tomcat.service.j2  # Adjust path as per your structure
    dest: "/etc/systemd/system/tomcat.service"
  notify: Restart Tomcat

- name: Start Tomcat service
  become: yes
  systemd:
    name: tomcat
    state: started
    enabled: yes

